config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: "users/registrations"}
  resources :users, only: [:edit, :update, :show]
  # For details on the DSL available within this filegit, see http://guides.rubyonrails.org/routing.html
  resources :items do
    resources :meetings, only: [:new, :create]
  end
  resources :meetings, only: [:edit, :update, :destroy]
  get '/meetings/:id/accept', to: 'meetings#accept', as: :accept_meeting
  get '/meetings/:id/decline', to: 'meetings#decline', as: :decline_meeting
  resources :items do
    resources :dispos, only: [:new, :create]
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :loser, class_name: "User", foreign_key: "user_id"
  has_one :user, through: :item
  belongs_to :dispo
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:new, :create, :edit, :update, :accept, :decline, :destroy]

  def new
    @meeting = Meeting.new
    authorize @meeting
  end

  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.loser = current_user
    authorize @meeting

    if @meeting.save
      redirect_to user_path(current_user)
    else
      render :item
    end
  end

  def show
  end

  def edit
  end

  def update
    # @meeting.loser = current_user
    # authorize @meeting
    # @meeting.update(meeting_params)
  end

  def accept
  end

  def decline
  end

  def destroy
    # @meeting.loser = current_user
    # /items/:item_id/meetings/:id
    @meeting = Meeting.find(params[:id])
    authorize @meeting
    @meeting.destroy
    redirect_to user_path(current_user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:dispo_id)
    end
  end

app/views/meetings/new.html.erb
<div class="container">
  <%= simple_form_for [@meeting] do |f| %>
    <% f.error_notification %>
    <%= f.input :start_date, label: "Debut des disponibilites", error: "Merci de donner vos disponibilites" %>
    <%= f.input :end_date, label: "Fin des disponibilites", error: "Merci de préciser la fin de vos dispos" %>
    <%= f.submit "Creer un meeting", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/meetings/show.html.erb
<div class="container">
  <div class="card card-show" style='background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= url %>);'>


    <h2 class="card-category"><%= @meeting.start_date %></h2>
    <div class="card-description-show">

       <li><%= @meeting.start_date %></li>
       <li><%= @meeting.end_date %></li>
       <li><%= @meeting.user.name %></li>
       <li><%= @meeting.item.name %></li>

 </div>

  <%= link_to "Retourner à la liste des meetings", meetings_path, class: "btn btn-primary" %>