config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: "users/registrations"}
  resources :users, only: [:edit, :update, :show]
  # For details on the DSL available within this filegit, see http://guides.rubyonrails.org/routing.html
  resources :items do
    resources :meetings, only: [:new, :create]
  end
  resources :meetings, only: [:edit, :update, :destroy]
  get '/meetings/:id/accept', to: 'meetings#accept', as: :accept_meeting
  get '/meetings/:id/decline', to: 'meetings#decline', as: :decline_meeting
  resources :items do
    resources :dispos, only: [:new, :create]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class= "footer-phrase">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook-square"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    </div>
  <div class="footer-copyright">
    OuKiLélé a été fait avec beaucoup d'<i class="fa fa-heart"></i> au Wagon
  </div>
</div>

app/views/shared/_form.html.erb
<% if policy(Item).new? %>

  <div class="form-container">
<!--       <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2 new"> -->
          <div class="new_form">
<!--           <h1> Détails de votre objet trouvé</h1> -->
          <%= simple_form_for @item do |f| %>
            <%= f.input :category, label: "Catégorie de l'objet trouvé", collection: Item::CATEGORIES, error: "Merci de préciser la catégorie de l'objet", class: "select2",selected: 1 %>
            <%= f.input :name, label: "Nom de l'objet", error: "Merci de préciser le type d'objet", required: true, include_blank: false, placeholder: "Un lapinou" %>
            <%= f.input :description, label: "Plus de précisions sur l'objet", error: "Merci de décrire précisément l'objet", placeholder: "Un doudou bleu et rouge..."%>
            <%= f.input :location, label: "Adresse où l'objet a été trouvé", error: "Merci de préciser où l'objet a été trouvé" %>
            <%#= f.input :location_detailed, label: "Endroit précis où l'objet a été trouvé", error: "Merci de préciser l'endroit où l'objet a été trouvé", placeholder: "Dans le train 4687 en provenance Paris, dans le bus 82..." %>
            <%= f.input :date_found, label: "Date à laquelle l'objet a été trouvé", error: "Merci de préciser la date à laquelle l'objet a été trouvé", input_html: {type: :date, class: "datepicker"} %>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <%= f.input :start_date, label: "Quand êtes-vous disponible pour rendre cet objet?", error: "Merci de donner vos disponibilités", input_html: {type: :date, value: Time.now.strftime('%d-%m-%Y'), class: "range"} %>
            <%#= f.input :end_date, label: "Fin des disponibilités", error: "Merci de préciser la fin de vos disponibilités", input_html: {type: :date, value: Time.now.strftime('%d-%m-%Y'), class: "range"} %>
            <%= f.submit "Mettre en ligne l'objet trouvé", class: "btn btn-info" %>
          <% end %>
        </div>
<!--       </div>
    </div> -->
  </div>
<% end %>

app/views/shared/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel">Récupère ton <%=@item.name %>!, <%= current_user.first_name %> </h3>
      </div>
      <div class="modal-body">
        <%= cl_image_tag @item.finder.photo, height: 150, width: 150, crop: :fill, class: "avatar-meeting-modal" %>
        <br>
        <br>
        <h4><%= @item.finder.first_name %> est disponible aux dates suivantes:</h4>
        <% @dispos.each do |dispo| %>
              <%= dispo.start_date %><%= simple_form_for [@item, Meeting.new] do |f| %>
              <%= f.input :dispo_id, as: :hidden, input_html: { value: dispo.id } %>
              <%= f.submit "Accept", class: "btn btn-primary sweet-alert-button" %>
              <% end %>
              <%= dispo.end_date %><%= simple_form_for [@item, Meeting.new] do |f| %>
              <%= f.input :dispo_id, as: :hidden, input_html: { value: dispo.id } %>
              <%= f.submit "Accept", class: "btn btn-primary sweet-alert-button" %>
              <% end %>
              <br>
              <%= @item.location %>
          <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <h1 class="logo"> OuKiLélé?</h1>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <%= link_to "Tous les objets trouvés", items_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Ajouter un objet trouvé", new_item_path, class: "navbar-wagon-item navbar-wagon-link btn_hp" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Mon profil") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Me déconnecter") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Login link (when logged out) -->
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><%= link_to '#' do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_user_item_index.html.erb
<div class="items-content">
  <% @user_items.each do |item| %>
  <div class="card-user">
    <%= cl_image_tag item.photo, height: 200, width: 300, crop: :fill, class: "card-img-user" %>
    <div class="card-header">
      <h2 class="card-category-user">
        <%= item.category %>
      </h2>
      <div class="card-description-user">
        <h3> <%= item.name %></h3>
        <p> <%= item.location %> - <%= item.date_found %></p>
      </div>
    </div>
    <%= link_to "", item_path(item), class: "card-link-user" %>
    </div>
    <% end %>
  </div>

app/views/shared/_user_meetings.html.erb
<% @loser_meetings.each do |meeting| %>
<div class="product">
  <div class='product-upvote'>
  </div>
  <%= cl_image_tag meeting.dispo.item.finder.photo, height: 100, width: 100, crop: :fill, class: "product-image hidden-xs" %>
  <div class='product-body'>
    <h3><%= meeting.dispo.item.finder.first_name %></h3>
    <p><%= meeting.dispo.start_date %></p>
  </div>
  <div class="meetings-flex">
    <h3><%= meeting.dispo.item.name %></h3>
    <p><%= meeting.dispo.item.location %></p>
  </div>
    <%= link_to "Je l'ai!", meeting_path(meeting),
      method: :delete, class: "btn btn-danger meeting-delete-btn"
      %>
</div>
<% end %>
<% @finder_meetings.each do |meeting| %>
<div class="product">
  <div class='product-upvote'>
  </div>
  <%= cl_image_tag meeting.dispo.item.finder.photo, height: 100, width: 100, crop: :fill, class: "product-image hidden-xs" %>
  <div class='product-body'>
    <h3><%= meeting.loser.first_name %></h3>
    <p><%= meeting.dispo.start_date %></p>
  </div>
  <div class="meetings-flex">
    <h3><%= meeting.dispo.item.name %></h3>
    <p><%= meeting.dispo.item.location %></p>
  </div>
    <%= link_to "Je l'ai!", meeting_path(meeting),
      method: :delete, class: "btn btn-danger meeting-delete-btn"
      %>
</div>
<% end %>