config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: "users/registrations"}
  resources :users, only: [:edit, :update, :show]
  # For details on the DSL available within this filegit, see http://guides.rubyonrails.org/routing.html
  resources :items do
    resources :meetings, only: [:new, :create]
  end
  resources :meetings, only: [:edit, :update, :destroy]
  get '/meetings/:id/accept', to: 'meetings#accept', as: :accept_meeting
  get '/meetings/:id/decline', to: 'meetings#decline', as: :decline_meeting
  resources :items do
    resources :dispos, only: [:new, :create]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :finder, class_name: "User", foreign_key: "user_id"
  has_many :dispos
  # belongs_to :user
  mount_uploader :photo, PhotoUploader
  has_many :dispos, dependent: :destroy
  validates :category, presence: true
  validates :date_found, presence: true
  validates :location, presence: true
  validates :name, presence: true, unless: :skip_if_item_creation
  validates :photo, presence: true

  attr_accessor :skip_if_item_creation

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?


  CATEGORIES = ["Bijoux", "Électronique", "Papiers d'identité", "Peluche", "Vêtements",  "Divers"]

  def skip_if_item_creation
    self.id.nil? && !self.category.nil? && !self.date_found.nil? && !self.location.nil?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = policy_scope(Item).order(created_at: :desc)
    @items = @items.where("lower(category) LIKE ?",params[:query_category].downcase) if params[:query_category].present?
    @items = @items.near(params[:query_location], 10) if params[:query_location].present?
    # @items = @items.where("lower(category) LIKE ?",params[:query_category]) if params[:query_category].present?
    # if params[:query_category].present?
    #   @items = @items.where("lower(category) LIKE","%#{params[:query_category]}%")
    # else
    #   @items = policy_scope(Item).order(created_at: :desc)
    #   @items = Item.where.not(latitude: nil, longitude: nil)
    # end
    @items = @items.where.not(latitude: nil, longitude: nil)
    @markers = @items.map do |item|
      {
        lat: item.latitude,
        lng: item.longitude
      }
    end
  end

  def show
    @item = Item.find(params[:id])
    @dispos = @item.dispos
    authorize @item
  end

  def new
    @item = Item.new
    @dispo = Dispo.new
    # @item.dispos = @dispo
    authorize @item
    authorize @dispo
  end

  def create
    @dispo = Dispo.new(dispo_params)
    @item = Item.new(item_params)
    @item.dispos << @dispo
    @item.finder = current_user
    authorize @item
    authorize @dispo
    if @item.save
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    @item.finder = current_user
    authorize @item
  end

  def update
    @item = Item.find(params[:id])
    @item.finder = current_user
    authorize @item
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.finder = current_user
    authorize @item
    @item.destroy
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :category, :description, :date_found, :location, :location_detailed, :photo, :reward)
  end

  def dispo_params
    params.require(:item).permit(:start_date, :end_date)
  end
end

app/views/items/edit.html.erb
<%= render 'shared/form', item: @item %>

app/views/items/index.html.erb
<div id="results-container">

  <% if params[:query_category].present? ||
    params[:query_location] %>
  <div class = "container" id="filters-container">
    <h3 style="font-size: 18px" id= "search-more">Résultats de la recherche: </h3>
    <div id="query">
      <strong> Catégorie: </strong>
      <% if params[:query_category].present? %>
      <em>  <%= params[:query_category]%>   </em>
      <% else %>
      <em>  Tous les objets trouvés   </em>
      <% end %>
    </div>
    <div id="query">
      <strong> Lieu: </strong>
      <% if params[:query_location].present? %>
      <em><%= params[:query_location].downcase.slice(0, 30)%>..  </em>
      <% else %>
      <em>  partout    </em>
      <% end %>
    </div>
    <br>
    <h3 style="font-size: 18px" id= "search-more"> Mettre à jour ma recherche: </h3>
    <div class = "search-bar2">
      <i class="fas fa-search" id = "search-magnifier2">  </i>
      <%= form_tag items_path, method: :get, class: "form-inline" do %>
      <div class="form-group">
        <%= select_tag :query_category,
        options_for_select(["Bijoux", "Électronique", "Papiers d'identité", "Peluche", "Vêtements",  "Divers"], params[:query_category]),
        include_blank: "Catégorie",
        style: "width: 120px",
        class: "form-control"
          %>
        </div >
            <!-- div class="form-group">
              <%#= text_field_tag :name,
                params[:name],
                class: "form-control"
              %>
            </div> -->
            <div class="form-group">
              <%= text_field_tag :query_location,
              params[:query_location],
              class: "form-control",
                id: "item_location",
                placeholder: "Où?"
                %>
              </div>

              <button type="submit" class = "btn btn-info"> Go! </button>
              <% end %>
    </div>
  </div>
  <% end %>

          <div class="content-index">
            <div class="container-index" id="search-results">
              <div>
                <h4 class="item-index-header text-center"> <%= @items.length %> résultat(s) trouvé(s)</h4>
                <div class="row">
                  <% @items.each do |item| %>
                  <%# url = image_path('default.jpg') %>
                  <div class="col-xs-12 col-sm-3 col-md-4">
                    <div class="card-index" id="search-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path item.photo, height: 300, width: 400, crop: :fill %>')">
                      <div class="card-header">
                        <h2 class="card-category-index">
                          <%= link_to item.name, item_path(item) %>
                        </h2>
                        <div class="card-description-index text-left">
                        <p> <%= Date.parse(item.date_found).strftime('%d-%m-%Y') %></p>

                        </div>
                      </div>
                    </div>
                 <!--    <div class="text-left card-info-index">
                        <p> <%= item.location %></p>
                    </div> -->
                  </div>
                  <% end %>
                </div>
              </div>
              <div
              id="map"
              style="width: 100%;
              height: 100%;"
              data-markers="<%= @markers.to_json %>"
              ></div>
            </div>
          </div>

        </div>

app/views/items/new.html.erb
<% if policy(Item).new? %>
<%= render 'shared/form', item: @item %>

<% end %>

app/views/items/show.html.erb
<div class="item-show">
  <div class="item-show-photo">
    <div> <%= cl_image_tag @item.photo, height: 200, width: 300, crop: :fill %></div>
    <div class="buttons" id="show-buttons">
<!--       <button type="button" id="set-meeting" class="btn btn-primary">Meeting</button> -->
      <br>
      <p>Disponibilités du trouveur</p>
      <% @dispos.each do |dispo| %>
      <br>
        du <%= dispo.start_date %>
        <br>
        <%#= dispo.end_date %>
        <br>
      <% end %>
      <br>
      <%# if policy(@item).update? %>
      <%#= link_to "Ajouter des disponibilités pour rendre l'objet", new_item_dispo_path(@item), class: "btn btn-success" %>
      <%# end %>
      <%#= link_to "Retourner à la liste", items_path, class: "btn btn-success" %>
    </div>
  </div>
  <div class="item-show-details">
    <br>
    <h4>Nom:</h4> <%= @item.name %>
    <h4>Catégorie</h4> <%= @item.category %>
    <h4>Description</h4> <%= @item.description %>
    <h4>Date où l'objet a été trouvé</h4> <%= l(Date.parse(@item.date_found), format: :long) %>
    <div><h4>Lieu:</h4> <%= @item.location %><%= @item.location_detailed %></div>
  </div>
  <div class = "show-items-buttons">
      <br>
      <br><br><br><br>
      <br>
      <% if policy(@item).update? %>
      <%= link_to "Mettre à jour l'objet", edit_item_path(@item.id), class: "btn btn-info"%>
      <% end %>
      <% if policy(@item).destroy? %>
      <%= link_to "Effacer cet objet", item_path(@item.id),
      method: :delete,
      data: { confirm: "Voulez-vous vraiment effacer cet objet ?" },
      class: "btn btn-info", id: "sweet-alert-demo" %>
      <% end %>
      <% unless @item.finder == current_user %>
      <button type="button" class="btn btn-info set-meeting-button" data-toggle="modal" data-target="#exampleModal">
      C'est mon <%= @item.name %> !
      </button>
      <%= render 'shared/modal' %>
      <% end %>
  </div>
</div>